version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-object-hour
    ports:
      - "8080:8080"
    environment:
      # Database Configuration (Supabase)
      - DB_HOST=aws-1-ap-south-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres.ykdfyoirtmkscsygyedr
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
